#!/usr/bin/env node
// Stage: shotlist → assembled HyperFrames project.
//
// Reads brand/tokens.json + <video>/brief.md (copy) + <video>/shotlist.yaml and writes:
//   <video>/index.html          root composition: one slot per shot (timing from shotlist) + mixed audio
//   (in memory) one standalone root per shot, used by review/render for solo shots
//   <video>/assets/…            brand fonts + marks copied in (the project must be self-contained)
// Scenes never hardcode copy or timing: they read window.__TALEX__ injected here.
//
// usage: node pipeline/build.mjs [videos/<name>]
import fs from "node:fs";
import path from "node:path";
import { REPO, loadVideo, writeIfChanged, rel } from "./lib.mjs";

// GSAP is vendored (pipeline/runtime/vendor) — the render browser must not depend on a CDN.
const GSAP = "assets/vendor/gsap.min.js";

export function build(arg) {
  const { dir, tokens, copy, shotlist } = loadVideo(arg);
  const v = shotlist.video;
  const fps = v.fps || tokens.format.fps;

  // 1. assets
  const assets = path.join(dir, "assets");
  fs.mkdirSync(path.join(assets, "fonts"), { recursive: true });
  fs.mkdirSync(path.join(assets, "brand"), { recursive: true });
  fs.mkdirSync(path.join(assets, "vendor"), { recursive: true });
  const copies = [
    [tokens.fonts.display.file, "fonts/Archivo-Variable.woff2"],
    ["brand/talex-x-mark.svg", "brand/talex-x-mark.svg"],
    ["brand/talex-x-mark-mono.svg", "brand/talex-x-mark-mono.svg"],
    ["brand/talex-logo.svg", "brand/talex-logo.svg"],
    ["brand/talex-logo-dark.svg", "brand/talex-logo-dark.svg"],
    ["pipeline/runtime/vendor/gsap.min.js", "vendor/gsap.min.js"],
    ["pipeline/runtime/talex-fx.js", "vendor/talex-fx.js"],
  ];
  for (const [src, dst] of copies) {
    const a = fs.readFileSync(path.join(REPO, src));
    const out = path.join(assets, dst);
    if (!fs.existsSync(out) || !a.equals(fs.readFileSync(out))) fs.writeFileSync(out, a);
  }
  const xMarkPaths = [...fs.readFileSync(path.join(REPO, "brand/talex-x-mark.svg"), "utf8").matchAll(/<path d="([^"]+)"/g)].map((m) => m[1]);
  // full logo lockup as path data so scenes can draw it inline (deterministic, recolorable):
  // paths[0] = wordmark (white on dark / black on light), paths[1] = green mark part
  const logoSvg = fs.readFileSync(path.join(REPO, "brand/talex-logo.svg"), "utf8");
  const logo = {
    viewBox: logoSvg.match(/viewBox="([^"]+)"/)[1],
    paths: [...logoSvg.matchAll(/<path d="([^"]+)" fill="([^"]+)"/g)].map((m) => ({ d: m[1], fill: m[2] })),
  };

  // 2. data handed to scenes
  const shots = {};
  for (const s of shotlist.shots) shots[s.id] = s;
  const data = { video: v, copy, tokens, shots, brand: { xMarkViewBox: "272 0 98 66", xMarkPaths, logo } };

  const c = tokens.colors;
  const cssVars = [
    `--tx-green:${c.green}`,
    `--tx-black:${c.black}`,
    `--tx-white:${c.white}`,
    `--tx-violet:${c.violet}`,
    `--tx-green-hot:${c.green_hot}`,
    `--tx-green-deep:${c.green_deep}`,
    `--tx-glass-top:${c.glass_top}`,
    `--tx-glass-bottom:${c.glass_bottom}`,
    `--tx-wash-green:${c.wash_green}`,
    `--tx-wash-blue:${c.wash_blue}`,
    `--tx-halftone-light:${c.halftone_on_white}`,
    `--tx-halftone-dark:${c.halftone_on_dark}`,
    `--tx-display-weight:${tokens.fonts.display.weight}`,
    `--tx-display-stretch:${tokens.fonts.display.stretch}`,
    `--tx-display-tracking:${tokens.fonts.display.letter_spacing}`,
    `--tx-caption-weight:${tokens.fonts.caption.weight}`,
    `--tx-caption-stretch:${tokens.fonts.caption.stretch}`,
    `--tx-caption-tracking:${tokens.fonts.caption.letter_spacing}`,
    `--tx-bloom:${tokens.glow.bloom_rest.shadow}`,
    `--tx-vignette:${tokens.glow.vignette}`,
  ].join(";");

  const W = v.width, H = v.height;

  const head = (title) => `<!doctype html>
<!-- GENERATED by pipeline/build.mjs from shotlist.yaml + brief.md + brand/tokens.json. Do not edit by hand: edit the sources and run \`npm run build\`. -->
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=${W}, height=${H}" />
    <title>${title}</title>
    <script src="${GSAP}"></script>
    <style>
      @font-face {
        font-family: "Archivo";
        src: url("assets/fonts/Archivo-Variable.woff2") format("woff2");
        font-weight: 100 900;
        font-stretch: 62% 125%;
        font-display: block;
      }
      :root { ${cssVars}; }
      * { margin: 0; padding: 0; box-sizing: border-box; }
      html, body { margin: 0; width: ${W}px; height: ${H}px; overflow: hidden; background: ${c.black}; }
      #root { position: relative; width: 100%; height: 100%; overflow: hidden; background: ${c.black}; }
      #root > div[data-composition-src] { position: absolute; inset: 0; }
    </style>
    <script id="talex-data">
      window.__TALEX__ = ${JSON.stringify(data)};
    </script>
    <script src="assets/vendor/talex-fx.js"></script>
  </head>`;

  const slot = (s, start, track) => {
    const dur = +(s.end - s.start + (s.tail || 0)).toFixed(4);
    const id = path.basename(s.scene, ".html");
    return `      <div
        id="el-${s.id}"
        data-composition-id="${id}"
        data-composition-src="${s.scene}"
        data-start="${start}"
        data-duration="${dur}"
        data-track-index="${track}"
        data-width="${W}"
        data-height="${H}"
      ></div>`;
  };

  // 3. root index.html — all shots + mixed audio
  const mixRel = "assets/audio/mix.wav";
  const hasMix = fs.existsSync(path.join(dir, mixRel));
  const index = `${head(v.title)}
  <body>
    <div id="root" data-composition-id="main" data-width="${W}" data-height="${H}" data-duration="${v.duration}" data-fps="${fps}">
${shotlist.shots.map((s, i) => slot(s, s.start, i + 1)).join("\n")}
${hasMix ? `      <audio id="mix" src="${mixRel}" data-start="0" data-duration="${v.duration}" data-track-index="10" data-volume="1"></audio>` : "      <!-- no mix yet: run `npm run mix` then `npm run build` -->"}
    </div>
    <script>
      window.__timelines["main"] = gsap.timeline({ paused: true });
    </script>
  </body>
</html>
`;
  const changed = [];
  if (writeIfChanged(path.join(dir, "index.html"), index)) changed.push("index.html");

  // 4. one standalone root per shot (picture only) — kept in memory; review/render write it
  //    into a temp copy of the project (a second root .html inside the project trips lint).
  const solos = {};
  for (const s of shotlist.shots) {
    const dur = +(s.end - s.start + (s.tail || 0)).toFixed(4);
    solos[s.id] = `${head(`${s.id} solo`)}
  <body>
    <div id="root" data-composition-id="main" data-width="${W}" data-height="${H}" data-duration="${dur}" data-fps="${fps}">
${slot(s, 0, 1)}
    </div>
    <script>
      window.__timelines["main"] = gsap.timeline({ paused: true });
    </script>
  </body>
</html>
`;
  }
  console.log(`build ${rel(dir)}: ${changed.length ? "wrote " + changed.join(", ") : "up to date"}${hasMix ? "" : " (no audio mix yet)"}`);
  return { dir, shotlist, solos };
}

if (import.meta.url === `file://${process.argv[1]}`) build(process.argv[2]);

/** Write a self-contained single-shot project (index.html = that shot only) into `outDir`. */
export function makeSoloProject(built, id, outDir) {
  fs.rmSync(outDir, { recursive: true, force: true });
  fs.mkdirSync(outDir, { recursive: true });
  for (const d of ["scenes", "assets"]) fs.cpSync(path.join(built.dir, d), path.join(outDir, d), { recursive: true });
  fs.copyFileSync(path.join(built.dir, "hyperframes.json"), path.join(outDir, "hyperframes.json"));
  fs.writeFileSync(path.join(outDir, "index.html"), built.solos[id]);
  return outDir;
}
