#!/usr/bin/env node
// Stage: cue sheet. Flattens every sfx cue in shotlist.yaml (plus the music bed) into
// <video>/audio_cues.yaml with exact times in ms and frames. Run after the picture is locked;
// mix.mjs reads ONLY this file, and `npm run check` fails if it is stale.
//
// usage: node pipeline/cues.mjs [videos/<name>]
import fs from "node:fs";
import path from "node:path";
import YAML from "yaml";
import { REPO, loadVideo, writeIfChanged, rel } from "./lib.mjs";

export function cueSheet(arg) {
  const { dir, shotlist } = loadVideo(arg);
  const lib = YAML.parse(fs.readFileSync(path.join(REPO, "audio/sfx/prompts.yaml"), "utf8"));
  const v = shotlist.video;
  const fps = v.fps;
  const ms = (s) => Math.round(s * 1000);
  const events = [];
  for (const s of shotlist.shots) {
    for (const c of s.sfx || []) {
      const snd = lib.sounds[c.sound];
      if (!snd) throw new Error(`${s.id}.${c.cue}: unknown sound ${c.sound}`);
      const duck = snd.duck ?? (snd.category === "hit" || snd.category === "motion");
      events.push({
        at_ms: ms(c.at),
        frame: Math.round(c.at * fps),
        shot: s.id,
        cue: c.cue,
        sound: c.sound,
        file: `audio/sfx/${c.sound}.mp3`,
        gain_db: c.gain_db ?? 0,
        category: snd.category,
        duck,
        ...(snd.trim_exact ? { length_ms: ms(snd.duration_s), ends_at_ms: ms(c.at) + ms(snd.duration_s) } : {}),
        ...(snd.shape_db ? { shape_db: snd.shape_db } : {}),
        ...(c.note ? { note: c.note } : {}),
      });
    }
  }
  events.sort((a, b) => a.at_ms - b.at_ms || a.cue.localeCompare(b.cue));
  const m = v.mix || {};
  const planFile = v.music_plan ? path.join(REPO, v.music_plan) : null;
  const plan = planFile && fs.existsSync(planFile) ? JSON.parse(fs.readFileSync(planFile, "utf8")) : {};
  const sheet = {
    video: v.id,
    fps,
    duration_ms: ms(v.duration),
    music: {
      file: v.music,
      plan: v.music_plan,
      drop_ms: ms(v.music_drop),
      offset_ms: plan.measured?.offset_ms ?? 0,
      gain_db: m.music_gain_db ?? -6,
      build_ramp_db: m.music_build_ramp_db ?? [0, 0],
      duck_db: m.duck_db ?? 8,
      duck_release_ms: m.duck_release_ms ?? 260,
      fade_out_ms: (m.music_fade_out ?? [v.duration - 0.5, v.duration]).map(ms),
    },
    master: { loudness_lufs: m.loudness_lufs ?? -14, true_peak_db: m.true_peak_db ?? -1 },
    events,
  };
  const text = `# GENERATED by pipeline/cues.mjs from shotlist.yaml (+ audio/sfx/prompts.yaml). Do not edit by hand:\n# change a cue in shotlist.yaml, then \`npm run cues && npm run mix\`.\n${YAML.stringify(sheet, { lineWidth: 0 })}`;
  return { dir, sheet, text };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const { dir, sheet, text } = cueSheet(process.argv[2]);
  const f = path.join(dir, "audio_cues.yaml");
  console.log(`cues ${rel(f)}: ${writeIfChanged(f, text) ? "written" : "up to date"} (${sheet.events.length} events)`);
  for (const e of sheet.events) console.log(`  ${String(e.at_ms).padStart(5)} ms  f${String(e.frame).padStart(3)}  ${e.shot} ${e.cue.padEnd(15)} ${e.sound}`);
}
